language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
  - "pypy3"

install:
  - pip install .
  - pip install -r requirements_for_tests.txt

script: make test
after_success:
  coveralls
